baseURL = 'https://jagra26.github.io/peld_test/'
languageCode = 'pt-br'
title = 'Site de teste do Peld'
theme = 'FixIt'
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"
[params.header.title]
      # URL of the LOGO
      logo = 'https://github.com/jagra26/peld_test/blob/main/static/LOGO%20COSTA%20DOS%20CORAIS%20VERSAO%20SEM%20ESTACA%20-%20PELD.png?raw=true'
[markup.goldmark.renderer]
unsafe = true