baseURL = 'https://jagra26.github.io/peld_test/'
languageCode = 'pt-br'
title = 'Site de teste do Peld'
theme = 'FixIt'
[markup]
  _merge = "shallow"
[outputs]
  _merge = "shallow"
[taxonomies]
  _merge = "shallow"
[params.header.title]
      # URL of the LOGO
      logo = 'https://lh3.googleusercontent.com/US0NEjKykYUcPE4CgGbLC9YlkK1E384fzRLUbgaE7XKmu9JiQBvxzsv1YKdE76Tqf1aiym9rUriLpv9_JLzrld0=w16383'
[markup.goldmark.renderer]
unsafe = true